#!/bin/sh

set -e

# troubleshooting permissions shenanigans
whoami
ls -la ./PivotalDevOpsTutorial/ci/smplmonspec.json
ls -la ./PivotalDevOpsTutorial/ci/smplpipelineinfo.json

#echo "configuring Dynatrace CLI with $apitoken and $tenanthost"

#python /dtcli/dtcli.py config apitoken $apitoken tenanthost $tenanthost

#echo "initializing Dynatrace Custom Device to store timeseries performance data"

#python /dtcli/dtcli.py monspec pushdeploy ./PivotalDevOpsTutorial/ci/smplmonspec.json ./PivotalDevOpsTutorial/ci/smplpipelineinfo.json
