#!/bin/bash

set -e

#using container that already has alpine installed for speeeeeeeed!
#echo "Installing artillery for load tests: https://artillery.io/docs/getting-started/"
#npm install -g artillery

#export NEXT_APP_COLOR=$(cat ./current-app-info/next-app.txt)
export NEXT_APP_URL=http://$PCF_APP_SUFFIX.$PCF_APP_DOMAIN/

echo "Running artillery load tests against $NEXT_APP_URL..."

#artillery quick --duration 10 --rate 10 $NEXT_APP_URL
artillery run -t $NEXT_APP_URL ./PivotalDevOpsTutorial/ci/tasks/artillery-script.yml
