#!/bin/sh

set -xe

echo "configuring Dynatrace CLI with $apitoken and $tenanthost and enabling debug to show Dynatrace API calls"

python /dtcli/dtcli.py config apitoken $apitoken tenanthost $tenanthost debug 1
export NEXT_APP_COLOR=$(cat ./current-app-info/next-app.txt)
#export monspecserviceenvironment=SampleJSonService/Production-Green
eval monspecserviceenvironment=$monspecserviceenvironment
echo "Pushing Dynatrace monspec data for $monspecserviceenvironment after waiting 120s for data to hit Dynatrace"
sleep 120
echo "Current seconds since epoch is $(date -u +%s)"
#below doesn't work on busybox :(
#echo "Current milliseconds since epoch 2 minutes ago is $(date --date='120 seconds ago' -u +%s%3N)"
#echo "Current milliseconds since epoch 5 minutes ago is $(date --date='300 seconds ago' -u +%s%3N)"

python /dtcli/dtcli.py monspec push ./PivotalDevOpsTutorial/ci/smplmonspec.json ./PivotalDevOpsTutorial/ci/smplpipelineinfo.json $monspecserviceenvironment 6 1