#!/bin/sh

set -e

echo "configuring Dynatrace CLI with $apitoken and $tenanthost"

python /dtcli/dtcli.py config apitoken $apitoken tenanthost $tenanthost

echo "Pushing Dynatrace monspec data for $monspecserviceenvironment"

python /dtcli/dtcli.py monspec push ./PivotalDevOpsTutorial/ci/smplmonspec.json ./PivotalDevOpsTutorial/ci/smplpipelineinfo.json $monspecserviceenvironment 180 0