#!/bin/sh

set -xe

echo "configuring Dynatrace CLI with $apitoken and $tenanthost"

python /dtcli/dtcli.py config apitoken $apitoken tenanthost $tenanthost

export NEXT_APP_COLOR=$(cat ./current-app-info/next-app.txt)
export CURRENT_APP_COLOR=$(cat ./current-app-info/current-app.txt)

eval monspeccomparison=$monspeccomparison

echo "Validating load test results via monspec comparison $monspeccomparison after 60s wait"
sleep 60

python /dtcli/dtcli.py monspec pushcompare ./PivotalDevOpsTutorial/ci/smplmonspec.json ./PivotalDevOpsTutorial/ci/smplpipelineinfo.json $monspeccomparison 60